### ISSUE TITLE
Security issue in logs

### ISSUE THREAD

**Issue by mycaule** [artefactory/nautilus-connectors-kit#171]
https://github.com/artefactory/artefactory-connectors-kit/blob/29fb5b20d832ea81ec7f179030cf9c4a1a40bac4/ack/utils/processor.py#L40

Credentials might be printed in logs because of this line.

**Comment by bibimorlet** [comment]
Therefore, should we remove this?

**Comment by mycaule** [comment]
Looks like there was already a piece of code for masking secrets such as `--ga-client-secret`, `--ga-access-token` 

https://github.com/artefactory/artefactory-connectors-kit/blob/29fb5b20d832ea81ec7f179030cf9c4a1a40bac4/ack/utils/processor.py#L34-L38

but it isn't working properly. I will investigate.
