### ISSUE TITLE
As a User, I can launch a request on any reader using a pre-defined date_range option

### ISSUE THREAD

**Issue by gabrielleberanger** [artefactory/nautilus-connectors-kit#82]
WHY
Currently, only specific readers accept a `--date_range` parameter (it depends of the source API, that offers it or not).

Such a pre-defined `--date_range` option can be very convenient, in particular when conducting tests. In this case, you just have to specify `--date-range PREVIOUS_WEEK` for instance, instead of providing a specific `--start-date` and `--end-date` for your request.

HOW
Make the `--date_range` option available to all readers, including when it is not initially provided by the source API.

**Comment by benoitgoujon** [comment]
Also see issue #67 for a description of how each reader handles date parameters.
